# ================================================
# 🌍 Terraform Azure DevOps Pipeline
# Author: Mohit | Infra: Azure | IaC: Terraform
# ================================================

parameters:
  - name: environment
    displayName: "Environment"
    type: string
    default: dev
    values:
      - dev
      - prod

# 🔔 Trigger branches
trigger:
  branches:
    include:
      - main
      - feature/*

# 👷 Agent Pool
pool:
  name: default

# ============================================================
# STAGE 1️⃣ : TERRAFORM INIT
# ============================================================
stages:
  - stage: terraform_init
    displayName: "Terraform Init"
    jobs:
      - job: terraform_init
        displayName: "Initialize Terraform"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
              backendServiceArm: 'todo-infra'  # Azure DevOps service connection
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'

# ============================================================
# STAGE 2️⃣ : TERRAFORM VALIDATE
# ============================================================
  - stage: terraform_validate
    displayName: "Terraform Validate"
    dependsOn: terraform_init
    jobs:
      - job: terraform_validate
        displayName: "Validate Terraform Code"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
              backendServiceArm: 'todo-infra'  # Azure DevOps service connection
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'

          - task: TerraformTask@5
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

# ============================================================
# STAGE 3️⃣ : TERRAFORM PLAN
# ============================================================
  - stage: terraform_plan
    displayName: "Terraform Plan"
    dependsOn: terraform_validate
    jobs:
      - job: terraform_plan
        displayName: "Plan Infrastructure"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'todo-infra'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
              publishPlanResults: 'true'

# ============================================================
# STAGE 4️⃣ : TERRAFORM APPLY
# ============================================================
  - stage: terraform_apply
    displayName: "Terraform Apply"
    dependsOn: terraform_plan
    condition: succeeded()
    jobs:
      - job: terraform_apply
        displayName: "Apply Infrastructure Changes"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'todo-infra'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
              args: '-auto-approve'
