parameters:
  - name: enviroment
    displayName: PARAMETERS
    type: string
    default: dev
    values:           
      - dev
      - prod

trigger:
  - main
  - feature/*

pool: default
stages:
  - stage: terraforminit
    displayName: TERRAFORM INIT
    jobs:
      - job: terraforminit
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'                                                 
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              backendServiceArm: 'todo-infra'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.enviroment }}.terraform.tfstate'
  - stage: terraformplan
    displayName: TERRAFORM PLAN
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.enviroment }}.terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              backendAzureRmKey: '${{ parameters.enviroment }}.terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              environmentServiceNameAzureRM: 'todo-infra'
  - stage: terraformapply
    displayName: TERRAFORM APPLY
    jobs:
      - job: terraformapply
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.enviroment }}.terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{ parameters.enviroment }}'
              environmentServiceNameAzureRM: 'todo-infra'