# ================================================
# 🌍 Terraform Azure DevOps Pipeline
# Author: Mohit | Infra: Azure | IaC: Terraform
# ================================================

parameters:
  - name: environment
    displayName: "Environment"
    type: string
    default: dev
    values:
      - dev
      - prod

# 🔔 Trigger branchess
trigger:
  branches:
    include:
      - main
      - feature/*

# 👷 Agent Pool
pool:
  name: default


# ============================================================
# STAGE 1️⃣ : TERRAFORM INIT
# ============================================================
stages:
  - stage: terraform_init
    displayName: "Terraform Init"
    jobs:
      - job: terraform_init
        displayName: "Initialize Terraform"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

# ============================================================
# STAGE 2️⃣ : TERRAFORM VALIDATE
# ============================================================
  - stage: terraform_validate
    displayName: "Terraform Validate"
    dependsOn: terraform_init
    jobs:
      - job: terraform_validate
        displayName: "Validate Terraform Code"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

          - task: TerraformTask@5
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

# ============================================================
# STAGE 3️⃣ : TERRAFORM PLAN (Feature + Main)
# ============================================================
  - stage: terraform_plan
    displayName: "Terraform Plan"
    dependsOn: terraform_validate
    jobs:
      - job: terraform_plan
        displayName: "Plan Infrastructure"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'todo-infra'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
              publishPlanResults: 'true'


# ============================================================
# STAGE 3️⃣ : CODE SCANNING
# ============================================================

  - stage: code_scanning
    displayName: "Code Scanning"
    dependsOn: terraform_plan
    jobs:
      - job: tfsec
        displayName: "TFSEC"
        steps: 
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
      - job: tflint
        displayName: "TroubleHog"
        steps: 
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: trufflehog git --no-update '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

      - job: checkov
        displayName: "Checkov"
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'checkov -d $(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

  
# ============================================================
# 🚦 MANUAL APPROVAL (Feature Branch Only)
# ============================================================
  - stage: manual_approval
    displayName: "Manual Approval Before Apply"
    dependsOn: terraform_plan
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
    jobs:
      - job: wait_for_approval
        displayName: "Wait for Manual Validation"
        pool: server
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 60
            inputs:
              notifyUsers: 'mohitstudy@gmail.com'
              instructions: 'Please review Terraform Plan output and approve if it looks good.'

# ============================================================
# STAGE 4️⃣ : TERRAFORM APPLY (Main Branch Only)
# ============================================================
  - stage: terraform_apply
    displayName: "Terraform Apply"
    dependsOn: terraform_plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: terraform_apply
        displayName: "Apply Infrastructure Changes"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'todo-infra'
              backendAzureRmResourceGroupName: 'NetworkWatcherRG'
              backendAzureRmStorageAccountName: 'remotebackendstgm'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'

          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'todo-infra'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
              args: '-auto-approve'
